### ISSUE TITLE
API Endpoint Broken on v2 Devices

### ISSUE THREAD

**Issue by DrDeke** [joeshaw/powerley-energybridge-homecontrol#1]
As of a couple days ago, it appears that DTE/Powerley have moved (or removed) the URL for the 'instantaneousdemand' API endpoint. Since that time, querying: 

http://ip_addr:8888/zigbee/se/instantaneousdemand

returns: 

{"code":"ResourceNotFound","message":"/zigbee/se/instantaneousdemand does not exist"}

instead of the instantaneousdemand value from the energy bridge device.

**Comment by joeshaw** [comment]
I see it as well on my device.  Here's another thread I found about it, without any answer as of yet.  https://community.home-assistant.io/t/dte-powerley-energy-bridge-endpoint-error/91160

I'll keep my eye on it, and see if I can reverse engineer any info out of my utility's app.

**Comment by joeshaw** [comment]
Another thread: https://forums.homeseer.com/forum/energy-management-plug-ins/energy-management-discussion/110557-utility-proviced-energy-bridge-how-to-get-info-into-homeseer
